'use strict';

const fs = require('fs');
const path = require('path');
const config = require('../config');

// Names always generated by the server (UUID + short extension) — never
// from the file's original name. This alone already prevents path
// traversal in stored names, but it's still validated thoroughly anyway.
const SAFE_STORED_NAME_RE = /^[a-fA-F0-9-]{36}(\.[a-zA-Z0-9]{1,10})?$/;

function isSafeStoredName(name) {
  return typeof name === 'string' && SAFE_STORED_NAME_RE.test(name);
}

function finalPath(storedName) {
  if (!isSafeStoredName(storedName)) return null;
  const resolved = path.resolve(config.finalDir, storedName);
  if (!resolved.startsWith(path.resolve(config.finalDir) + path.sep)) return null;
  return resolved;
}

function deleteStoredFile(storedName) {
  const p = finalPath(storedName);
  if (!p) return;
  fs.unlink(p, (err) => {
    if (err && err.code !== 'ENOENT') {
      // eslint-disable-next-line no-console
      console.error('Failed to delete file from storage:', err.code);
    }
  });
}

module.exports = { isSafeStoredName, finalPath, deleteStoredFile };
